export enum PreferredLanguage {
    english = 'ENGLISH',
    portugese = 'PORTUGESE',
    spanish = 'SPANISH',
    russian = 'RUSSIAN',
    french = 'FRENCH',
    georgian = 'GEORGIAN',
    chinese = 'CHINESE',
    indonesian = 'INDONESIAN',
    romanian = 'ROMANIAN',
    burmese = 'BURMESE',
    german = 'GERMAN',
    portuguese_brazil = 'PORTUGUESE_BRAZIL',
    vietnamese = 'VIETNAMESE',
    italian = 'ITALIAN',
    phrase = 'PHRASE',
  }